class BaseAnyCoinException(Exception): ...


class GetCoinQuotes(BaseAnyCoinException): ...


class CryptoCoinNotSupportedCMC(BaseAnyCoinException): ...


class ConverterCoinNotSupportedCMC(BaseAnyCoinException): ...


class CryptoCoinNotSupportedCGK(BaseAnyCoinException): ...


class ConverterCoinNotSupportedCGK(BaseAnyCoinException): ...
