class BaseAnyCoinException(Exception): ...


class GetCoinQuotes(BaseAnyCoinException): ...


class CoinNotSupportedCMC(BaseAnyCoinException): ...


class QuoteCoinNotSupportedCMC(BaseAnyCoinException): ...


class CoinNotSupportedCGK(BaseAnyCoinException): ...


class QuoteCoinNotSupportedCGK(BaseAnyCoinException): ...
